// Mock data for development and testing
import { Service, Provider, User, Entitlement } from '@/types';

export const mockServices: Service[] = [
  {
    id: '1',
    name: 'Sui RPC Node',
    description: 'High-performance RPC node service for Sui blockchain with 99.9% uptime guarantee. Perfect for dApps requiring reliable blockchain access.',
    provider_id: 'provider1',
    provider_name: 'Mysten Labs',
    category: 'RPC',
    type: 'Infrastructure',
    status: 'active',
    pricing: {
      type: 'tiered',
      tiers: [
        {
          id: 'free',
          name: 'Free Tier',
          price: 0,
          currency: 'SUI',
          features: ['100,000 requests/month', 'Community support', 'Standard endpoints'],
          rate_limits: {
            requests_per_minute: 10,
            requests_per_day: 3333,
          },
        },
        {
          id: 'pro',
          name: 'Pro',
          price: 50,
          currency: 'SUI',
          interval: 'monthly',
          features: ['1M requests/month', 'Priority support', 'Advanced analytics', 'Webhook notifications'],
          rate_limits: {
            requests_per_minute: 100,
            requests_per_day: 33333,
          },
        },
        {
          id: 'enterprise',
          name: 'Enterprise',
          price: 500,
          currency: 'SUI',
          interval: 'monthly',
          features: ['Unlimited requests', '24/7 dedicated support', 'Custom SLA', 'Private endpoints', 'Advanced security'],
          rate_limits: {
            requests_per_minute: 1000,
          },
        },
      ],
    },
    metadata: {
      endpoints: ['https://rpc.mainnet.sui.io', 'https://rpc.testnet.sui.io'],
      sla: {
        uptime_guarantee: '99.9%',
        response_time: '<100ms',
        support_hours: '24/7',
      },
      rate_limits: {
        requests_per_minute: 100,
        requests_per_day: 100000,
      },
      tokens_accepted: ['SUI', 'USDC'],
      documentation_url: 'https://docs.sui.io/build/rpc',
      support_url: 'https://discord.gg/sui',
      contact_email: 'support@mystenlabs.com',
      version: '2.0.0',
    },
    tags: ['verified', 'popular', 'mainnet', 'testnet'],
    verified: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-11-20T10:00:00Z',
  },
  {
    id: '2',
    name: 'Sui Indexer API',
    description: 'Advanced blockchain indexing service with real-time event tracking and historical data access. Query transactions, objects, and events efficiently.',
    provider_id: 'provider2',
    provider_name: 'SuiVision',
    category: 'Indexer',
    type: 'Data',
    status: 'active',
    pricing: {
      type: 'usage-based',
      tiers: [
        {
          id: 'payg',
          name: 'Pay As You Go',
          price: 0.01,
          currency: 'USDC',
          credits: 1000,
          features: ['Real-time indexing', 'Historical data', 'GraphQL API', 'REST API'],
          rate_limits: {
            requests_per_minute: 60,
          },
        },
      ],
    },
    metadata: {
      endpoints: ['https://api.suivision.xyz/graphql'],
      tokens_accepted: ['SUI', 'USDC', 'USDT'],
      documentation_url: 'https://docs.suivision.xyz',
      support_url: 'https://t.me/suivision',
      contact_email: 'contact@suivision.xyz',
      version: '1.5.2',
    },
    tags: ['indexer', 'graphql', 'real-time'],
    verified: true,
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-11-18T10:00:00Z',
  },
  {
    id: '3',
    name: 'Decentralized Storage',
    description: 'IPFS-based decentralized storage solution optimized for Sui NFTs and dApp assets. Store and retrieve data with cryptographic verification.',
    provider_id: 'provider3',
    provider_name: 'Web3Storage',
    category: 'Storage',
    type: 'Infrastructure',
    status: 'active',
    pricing: {
      type: 'subscription',
      tiers: [
        {
          id: 'starter',
          name: 'Starter',
          price: 10,
          currency: 'SUI',
          interval: 'monthly',
          features: ['10 GB storage', 'Unlimited bandwidth', 'IPFS pinning', 'CDN access'],
        },
        {
          id: 'growth',
          name: 'Growth',
          price: 50,
          currency: 'SUI',
          interval: 'monthly',
          features: ['100 GB storage', 'Unlimited bandwidth', 'IPFS + Arweave', 'CDN access', 'Priority support'],
        },
      ],
    },
    metadata: {
      endpoints: ['https://api.web3storage.io'],
      tokens_accepted: ['SUI', 'WAL'],
      documentation_url: 'https://docs.web3.storage',
      github_url: 'https://github.com/web3storage',
      version: '3.2.0',
    },
    tags: ['storage', 'ipfs', 'nft'],
    verified: false,
    created_at: '2024-03-05T10:00:00Z',
    updated_at: '2024-11-15T10:00:00Z',
  },
  {
    id: '4',
    name: 'Price Oracle Service',
    description: 'Reliable price feeds for DeFi applications with multi-source aggregation and manipulation resistance. Support for 100+ token pairs.',
    provider_id: 'provider4',
    provider_name: 'Pyth Network',
    category: 'Oracle',
    type: 'Data',
    status: 'active',
    pricing: {
      type: 'free',
      tiers: [
        {
          id: 'free',
          name: 'Free',
          price: 0,
          currency: 'SUI',
          features: ['Real-time price feeds', '100+ pairs', 'Sub-second updates', 'Community support'],
        },
      ],
    },
    metadata: {
      endpoints: ['https://hermes.pyth.network'],
      sla: {
        uptime_guarantee: '99.95%',
        response_time: '<50ms',
      },
      tokens_accepted: ['SUI'],
      documentation_url: 'https://docs.pyth.network',
      support_url: 'https://discord.gg/pyth',
      version: '1.0.0',
    },
    tags: ['verified', 'oracle', 'defi', 'free'],
    verified: true,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-11-19T10:00:00Z',
  },
  {
    id: '5',
    name: 'Sui Analytics Platform',
    description: 'Comprehensive blockchain analytics with custom dashboards, alerts, and reporting. Track wallet activity, smart contracts, and market trends.',
    provider_id: 'provider5',
    provider_name: 'SuiScan',
    category: 'Analytics',
    type: 'Tooling',
    status: 'beta',
    pricing: {
      type: 'tiered',
      tiers: [
        {
          id: 'basic',
          name: 'Basic',
          price: 25,
          currency: 'USDC',
          interval: 'monthly',
          features: ['5 custom dashboards', 'Basic alerts', 'CSV export', '30-day data retention'],
        },
        {
          id: 'professional',
          name: 'Professional',
          price: 100,
          currency: 'USDC',
          interval: 'monthly',
          features: ['Unlimited dashboards', 'Advanced alerts', 'API access', 'Webhook integration', '1-year data retention'],
        },
      ],
    },
    metadata: {
      endpoints: ['https://api.suiscan.xyz'],
      tokens_accepted: ['USDC', 'USDT'],
      documentation_url: 'https://docs.suiscan.xyz',
      contact_email: 'hello@suiscan.xyz',
      version: '0.9.0',
    },
    tags: ['analytics', 'beta', 'dashboards'],
    verified: false,
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-11-20T10:00:00Z',
  },
  {
    id: '6',
    name: 'Validator Infrastructure',
    description: 'Professional validator node hosting with automatic failover, monitoring, and performance optimization. Ideal for validators and staking services.',
    provider_id: 'provider6',
    provider_name: 'StakeNode',
    category: 'Validator',
    type: 'Infrastructure',
    status: 'active',
    pricing: {
      type: 'flat-rate',
      tiers: [
        {
          id: 'monthly',
          name: 'Monthly Plan',
          price: 200,
          currency: 'SUI',
          interval: 'monthly',
          features: ['Dedicated hardware', '24/7 monitoring', 'Auto-failover', 'Performance optimization', 'Technical support'],
        },
      ],
    },
    metadata: {
      sla: {
        uptime_guarantee: '99.99%',
        response_time: '<30ms',
        support_hours: '24/7',
      },
      tokens_accepted: ['SUI'],
      documentation_url: 'https://docs.stakenode.io',
      support_url: 'https://support.stakenode.io',
      contact_email: 'validators@stakenode.io',
      version: '2.1.0',
    },
    tags: ['verified', 'validator', 'enterprise'],
    verified: true,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-11-17T10:00:00Z',
  },
];

export const mockProviders: Provider[] = [
  {
    id: 'provider1',
    name: 'Mysten Labs',
    email: 'support@mystenlabs.com',
    wallet_address: '0x1234567890abcdef1234567890abcdef12345678',
    company: 'Mysten Labs',
    website: 'https://mystenlabs.com',
    verified: true,
    services_count: 3,
    created_at: '2024-01-10T10:00:00Z',
  },
  {
    id: 'provider2',
    name: 'SuiVision',
    email: 'contact@suivision.xyz',
    wallet_address: '0xabcdef1234567890abcdef1234567890abcdef12',
    company: 'SuiVision Inc',
    website: 'https://suivision.xyz',
    verified: true,
    services_count: 2,
    created_at: '2024-02-05T10:00:00Z',
  },
  {
    id: 'provider3',
    name: 'Web3Storage',
    email: 'contact@web3storage.io',
    company: 'Web3 Storage Solutions',
    website: 'https://web3.storage',
    verified: false,
    services_count: 1,
    created_at: '2024-03-01T10:00:00Z',
  },
];

export const mockUsers: User[] = [
  {
    id: 'user1',
    email: 'admin@suidiscovery.io',
    name: 'Admin User',
    role: 'admin',
    created_at: '2024-01-01T10:00:00Z',
  },
  {
    id: 'user2',
    email: 'developer@example.com',
    name: 'John Developer',
    role: 'developer',
    wallet_address: '0xdeveloper1234567890abcdef1234567890abcd',
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'user3',
    email: 'provider@example.com',
    name: 'Jane Provider',
    role: 'provider',
    wallet_address: '0xprovider1234567890abcdef1234567890abcdef',
    provider: mockProviders[0],
    created_at: '2024-01-15T10:00:00Z',
  },
];

export const mockEntitlements: Entitlement[] = [
  {
    id: 'ent1',
    user_id: 'user2',
    service_id: '1',
    tier_id: 'pro',
    status: 'active',
    credits_remaining: 750000,
    valid_until: '2025-01-20T10:00:00Z',
    created_at: '2024-11-20T10:00:00Z',
    transaction_hash: '0xtxhash123456789',
  },
  {
    id: 'ent2',
    user_id: 'user2',
    service_id: '4',
    tier_id: 'free',
    status: 'active',
    created_at: '2024-11-15T10:00:00Z',
  },
];
